### ISSUE TITLE
Possible mistake at sha256 cl file

### ISSUE THREAD

**Issue by deleterium** [bkerler/opencl_brute#17]
Hi!

I got the code for sha256 to use in my program but I found something strange. I use it to hash text passwords from 40 to 119 chars in length, but it produces wrong output when the password has 56-63 characters. The algorithm that is used is somewhat diferent from other implementation. It is faster but there is this caveat.

I got the code and compiled in C to check if the problem was in OpenCL, but the C code also produces wrong output for the 56-63 length.

I do not program in python, so I can not say that this problem affects you project, maybe the use case is less than 56 chars. If you find this relevant I can link the C code.

Best regards, Rui Santana.

**Comment by bkerler** [comment]
Hi, yes the algorithm was optimized for shorter messages, that's why it's faster. Fixing this however shouldn't be a big problem I guess.

**Comment by deleterium** [comment]
Thank you for fast answer! I changed the file in my project so it solves the hash for any input length. If you are interested these are the changes:

https://github.com/deleterium/signum-vanity-opencl/commit/78ebef87d19b08f7d7af525345d890d5a6a82935

I think the optimization grade is almost the same, just let me know if you want a PR for it.

By the way, neat code!

**Comment by bkerler** [comment]
Sure, a pr is always welcome ;)
