### ISSUE TITLE
sha256 number support ?

### ISSUE THREAD

**Issue by rockygsm** [bkerler/opencl_brute#2]
Hello
i hope you are fine my old friend.
do you plan add support sha256 8 digit may useful for many users.

**Comment by bkerler** [comment]
Can you please elaborate what you mean by 8 digit ? 

Because any hex value lower 32 bytes can be used, and sha256 is supported as well.

**Comment by rockygsm** [comment]
Hello
I mean 0 to 99999999 normal sha256. as i can see your implement is for hmac sha256.

**Comment by bkerler** [comment]
Hi, I will consider add this, but for now this repo is meant for pbkdf2 only.

**Comment by bkerler** [comment]
Hashing of SHA1 and SHA256 was added as standalone.
