### ISSUE TITLE
Increasing SHA256 hash length

### ISSUE THREAD

**Issue by likeaj6** [bkerler/opencl_brute#3]
`#SHA256 does support longer lengths, but inputbuffer and hash are limited to 32 chars`
Is there any way for me to edit the code to compute hashes of longer lengths (>32 chars)? If it helps, I only ever need to calculate one hash at a time, as opposed to an array of hashes.

Very new to OpenCL so appreciate any guidance.

**Comment by bkerler** [comment]
Commit 94d3ea5 shows how to increase hash size. Now upgraded to 64 chars :)

**Comment by jleo** [comment]
Hello,thanks for creating this kernal!
Can i make it support even longer by changing 64 to a larger number?like 80 or 120
